version: '3.8'
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: myappdb # اسم قاعدة البيانات
      POSTGRES_USER: user # اسم المستخدم
      POSTGRES_PASSWORD: password # كلمة المرور
    ports:
      - "5432:5432" # ربط المنفذ
    volumes:
      - pgdata:/var/lib/postgresql/data # تخزين دائم للبيانات
volumes:
  pgdata: